from collections.abc import MutableMapping
from re import Pattern
from typing import Any

from rest_framework.views import APIView
from typing_extensions import Self

class ViewInspector:
    header_regex: Pattern[str]
    instance_schemas: MutableMapping[Any, Any]
    _view: APIView | None
    def __init__(self) -> None: ...
    def __get__(self, instance: Any, owner: Any) -> Self: ...
    def __set__(self, instance: Any, other: Any) -> None: ...
    @property
    def view(self) -> APIView: ...
    @view.setter
    def view(self, value: APIView | None) -> None: ...
    def get_description(self, path: str, method: str) -> str: ...

class DefaultSchema(ViewInspector): ...
