class RemovedInDRF319Warning(DeprecationWarning): ...
class RemovedInDRF320Warning(PendingDeprecationWarning): ...

RemovedInNextDRFVersionWarning = RemovedInDRF319Warning
RemovedAfterNextDRFVersionWarning = RemovedInDRF320Warning
