from typing import Any, Dict, List, Protocol, Sequence, Type, Union

from django.db.models import Model, QuerySet
from django.views import View
from rest_framework.request import Request

SAFE_METHODS: Sequence[str] = ("GET", "HEAD", "OPTIONS")

class SupportsHasPermission(Protocol):
    def has_permission(self, request: Request, view: View) -> bool: ...
    def has_object_permission(self, request: Request, view: View, obj: Any) -> bool: ...

_PermissionClass = Union[Type[BasePermission], OperandHolder, SingleOperandHolder]

class OperationHolderMixin:
    def __and__(self, other: _PermissionClass) -> OperandHolder: ...
    def __or__(self, other: _PermissionClass) -> OperandHolder: ...
    def __rand__(self, other: _PermissionClass) -> OperandHolder: ...
    def __ror__(self, other: _PermissionClass) -> OperandHolder: ...
    def __invert__(self) -> SingleOperandHolder: ...

class SingleOperandHolder(OperationHolderMixin):
    operator_class: Type[Any]
    op1_class: _PermissionClass
    def __init__(self, operator_class: Type[Any], op1_class: _PermissionClass): ...
    def __call__(self, *args, **kwargs) -> SupportsHasPermission: ...

class OperandHolder(OperationHolderMixin):
    operator_class: Type[Any]
    op1_class: _PermissionClass
    op2_class: _PermissionClass
    def __init__(self, operator_class: Type[Any], op1_class: _PermissionClass, op2_class: _PermissionClass): ...
    def __call__(self, *args, **kwargs) -> SupportsHasPermission: ...

class AND:
    def __init__(self, op1: SupportsHasPermission, op2: SupportsHasPermission) -> None: ...
    def has_permission(self, request: Request, view: View) -> bool: ...
    def has_object_permission(self, request: Request, view: View, obj: Any) -> bool: ...

class OR:
    def __init__(self, op1: SupportsHasPermission, op2: SupportsHasPermission) -> None: ...
    def has_permission(self, request: Request, view: View) -> bool: ...
    def has_object_permission(self, request: Request, view: View, obj: Any) -> bool: ...

class NOT:
    def __init__(self, op1: SupportsHasPermission) -> None: ...
    def has_permission(self, request: Request, view: View) -> bool: ...
    def has_object_permission(self, request: Request, view: View, obj: Any) -> bool: ...

class BasePermissionMetaclass(OperationHolderMixin, type): ...

class BasePermission(metaclass=BasePermissionMetaclass):
    def has_permission(self, request: Request, view: View) -> bool: ...
    def has_object_permission(self, request: Request, view: View, obj: Any) -> bool: ...

class AllowAny(BasePermission): ...
class IsAuthenticated(BasePermission): ...
class IsAdminUser(BasePermission): ...
class IsAuthenticatedOrReadOnly(BasePermission): ...

class DjangoModelPermissions(BasePermission):
    perms_map: Dict[str, List[str]] = ...

    authenticated_users_only: bool = ...
    def get_required_permissions(self, method: str, model_cls: Type[Model]) -> List[str]: ...
    def _queryset(self, view: View) -> QuerySet: ...

class DjangoModelPermissionsOrAnonReadOnly(DjangoModelPermissions): ...

class DjangoObjectPermissions(DjangoModelPermissions):
    def get_required_object_permissions(self, method: str, model_cls: Type[Model]) -> List[str]: ...
