from typing import Any, Callable, Dict, List, MutableMapping, Optional

from rest_framework.request import Request

class BaseThrottle(object):
    def allow_request(self, request: Request, view) -> bool: ...
    def get_ident(self, request: Request) -> str: ...
    def wait(self) -> Optional[float]: ...

class SimpleRateThrottle(BaseThrottle):
    cache_format: str = ...
    cache: MutableMapping[str, Any] = ...
    history: List[object]
    key: Any = ...
    now: float
    rate: Optional[str]
    scope: Optional[str] = ...
    THROTTLE_RATES: Dict[str, Optional[str]] = ...
    timer: Callable[..., float] = ...
    def __init__(self) -> None: ...
    def get_cache_key(self, request: Request, view) -> Optional[str]: ...
    def get_rate(self): ...
    def parse_rate(self, rate: Any): ...
    def allow_request(self, request: Any, view: Any): ...
    def throttle_success(self) -> bool: ...
    def throttle_failure(self) -> bool: ...
    def wait(self): ...

class AnonRateThrottle(SimpleRateThrottle): ...
class UserRateThrottle(SimpleRateThrottle): ...

class ScopedRateThrottle(SimpleRateThrottle):
    scope_attr: str = ...
