from typing import Any, Optional

def apply_suffix_patterns(
    urlpatterns: Any, suffix_pattern: Any, suffix_required: Any, suffix_route: Optional[Any] = ...
): ...
def format_suffix_patterns(urlpatterns: Any, suffix_required: bool = ..., allowed: Optional[Any] = ...): ...
