from collections.abc import ItemsView
from typing import Any

from django import template
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AnonymousUser
from rest_framework.request import Request
from typing_extensions import override

register: Any
class_re: Any

def highlight_code(parser: Any, token: Any) -> CodeNode: ...

class CodeNode(template.Node):
    style: str
    lang: Any
    nodelist: Any
    def __init__(self, lang: Any, code: Any) -> None: ...
    @override
    def render(self, context: Any) -> str: ...

def render_markdown(markdown_text: Any) -> str: ...
def get_pagination_html(pager: Any) -> str: ...
def render_form(serializer: Any, template_pack: Any | None = ...) -> str: ...
def render_field(field: Any, style: Any) -> str: ...
def optional_login(request: Request) -> str: ...
def optional_docs_login(request: Request) -> str: ...
def optional_logout(request: Request, user: AnonymousUser | AbstractBaseUser, csrf_token: str) -> str: ...
def add_query_param(request: Request, key: str, val: Any) -> str: ...
def as_string(value: Any) -> str: ...
def as_list_of_strings(value: Any) -> list[str]: ...
def add_class(value: Any, css_class: Any) -> str: ...
def format_value(value: Any) -> str: ...
def items(value: Any) -> ItemsView[Any, Any] | list[Any]: ...
def add_nested_class(value: Any) -> str: ...

TRAILING_PUNCTUATION: Any
WRAPPING_PUNCTUATION: Any
word_split_re: Any
simple_url_re: Any
simple_url_2_re: Any
simple_email_re: Any

def smart_urlquote_wrapper(matched_url: Any) -> str | None: ...
