from typing import Any

from django.utils.datastructures import MultiValueDict

def is_html_input(dictionary: Any) -> bool: ...
def parse_html_list(dictionary: Any, prefix: str = "", default: Any | None = None) -> list[Any] | None: ...
def parse_html_dict(dictionary: Any, prefix: str = "") -> MultiValueDict[str, Any]: ...
