from typing import Any, Final

from django.utils.datastructures import MultiValueDict

NOT_PROVIDED: Final[object]

def is_html_input(dictionary: Any) -> bool: ...
def parse_html_list(dictionary: Any, prefix: str = "", default: Any | None = None) -> list[Any] | None: ...
def parse_html_dict(dictionary: Any, prefix: str = "", default: Any = ...) -> MultiValueDict[str, Any]: ...
