from collections.abc import Sequence

def datetime_formats(formats: Sequence[str]) -> str: ...
def date_formats(formats: Sequence[str]) -> str: ...
def time_formats(formats: Sequence[str]) -> str: ...
def humanize_strptime(format_string: str) -> str: ...
