from typing import Any

from _typeshed import Incomplete

def datetime_formats(formats: Any) -> Incomplete: ...
def date_formats(formats: Any) -> Incomplete: ...
def time_formats(formats: Any) -> Incomplete: ...
def humanize_strptime(format_string: Any) -> Incomplete: ...
