from _typeshed import Incomplete
from typing import Any

def datetime_formats(formats: Any) -> Incomplete: ...
def date_formats(formats: Any) -> Incomplete: ...
def time_formats(formats: Any) -> Incomplete: ...
def humanize_strptime(format_string: Any) -> Incomplete: ...
