from _typeshed import Incomplete
from typing import Any

def media_type_matches(lhs: Any, rhs: Any) -> Incomplete: ...
def order_by_precedence(media_type_lst: Any) -> Incomplete: ...

class _MediaType:
    orig: Any
    def __init__(self, media_type_str: Any) -> None: ...
    def match(self, other: Any) -> Incomplete: ...
    @property
    def precedence(self) -> Incomplete: ...
