from typing import Any

from _typeshed import Incomplete

def manager_repr(value: Any) -> Incomplete: ...
def smart_repr(value: Any) -> Incomplete: ...
def field_repr(field: Any, force_many: bool = ...) -> Incomplete: ...
def serializer_repr(serializer: Any, indent: Any, force_many: Any | None = ...) -> Incomplete: ...
def list_repr(serializer: Any, indent: Any) -> Incomplete: ...
