from typing import Any

from django.core.management.base import BaseCommand

UserModel: Any

class Command(BaseCommand):
    help: str = ...
    def create_user_token(self, username: Any, reset_token: Any): ...
    def add_arguments(self, parser: Any) -> None: ...
    def handle(self, *args: Any, **options: Any) -> None: ...
